### ISSUE TITLE
Duplicate startup constraint?

### ISSUE THREAD

**Issue by mtanneau** [ANL-CEEESA/UnitCommitment.jl#11]
## Description

The same constraint is created multiple times in the `MorLatRam2013` formulation for startup costs.
It won't cause any error, and it might be deliberate, but... an identical constraint `eq_startup_choose` is created for each startup type `s`, although by definition it doesn't depend on the startup type.

https://github.com/ANL-CEEESA/UnitCommitment.jl/blob/821d48bdc6c237df42107b170490b8470515c527/src/model/formulations/MorLatRam2013/scosts.jl#L15-L21

I think lines 16-21 should be outside the `for s in 1:S` loop, and should not be indexed by `s`.

## Steps to Reproduce

This occurs on the `dev` branch, commit [`821d48b`](https://github.com/ANL-CEEESA/UnitCommitment.jl/commit/821d48bdc6c237df42107b170490b8470515c527) at the time of writing

**Comment by iSoron** [comment]
Thank you for the bug report, @mtanneau. You are right, this constraint should be outside of the loop. PRs are welcome.
