### ISSUE TITLE
Extremely high memory usage (114 GB for a 8000 bus case) and unable to solve a single snapshot ED problem (no contingency)

### ISSUE THREAD

**Issue by mzy2240** [ANL-CEEESA/UnitCommitment.jl#41]
## Description

An incredible 114GB of memory usage observed during the optimization process, and failed in the third iteration.
![image](https://github.com/ANL-CEEESA/UnitCommitment.jl/assets/18620336/3759c2c9-7b08-42f6-921f-e28aedb133fa)

## Steps to Reproduce
[example2.txt](https://github.com/ANL-CEEESA/UnitCommitment.jl/files/12072444/example2.txt)
Rename to json file and load the instance to reproduce. Use HiGHS as the optimizer.

Please describe how can the developers reproduce the problem in their own computers. Code snippets and sample input files are specially helpful. For example:

1. Install the package
2. Run the code below with the attached input file...
3. The following error appears...

## System Information
 - Operating System: [e.g. Ubuntu 20.04] Windows 10
 - Julia version: [e.g. 1.4] 1.8.5
 - Package version: [e.g. 0.0.1] 0.3.0

**Comment by mzy2240** [comment]
I fixed the offer curve in the example. Considering it is just economic dispatch problem (not SCED), it should be very efficient to solve, and should not use 79 GB to handle a <10,000 bus case.

**Comment by mzy2240** [comment]
The extreme memory usage might be a memory leak, and seems to come from this code:
```julia
time_screening = @elapsed begin
        violations = []
        for sc in model[:instance].scenarios
            push!(
                violations,
                _find_violations(
                    model,
                    sc,
                    max_per_line = method.max_violations_per_line,
                    max_per_period = method.max_violations_per_period,
                ),
            )
        end
    end
```
The JuMP `model` itself does not introduce new variables or constraints in the above code in my example, so really no reason for such a huge memory usage (and more importantly, not GC-able).

**Comment by mzy2240** [comment]
Ok I am able to solve the problem by removing the custom offset for buses. So I think that's the reason. I am wondering if the default solution method has to work with the hardcoded bus offsets @iSoron

**Comment by iSoron** [comment]
@mzy2240 I'm still investigating this issue, but the package should maintain the bus sequence from the input file. If, for any reason,  you would like a certain bus to be the slack, you can list it first.

**Comment by iSoron** [comment]
@mzy2240 For this bug report, could you please confirm that no changes have been made to the source code of the package? Are you experiencing this behavior on a clean copy of the `dev` branch?

**Comment by mzy2240** [comment]
Yes still experience the same issue in a clean copy of the `dev` branch without any changes on the source code. The Windows machine is a dual socket workstation just fyi. Maybe it has something to do with the dual socket setup?

**Comment by mzy2240** [comment]
Should be a false alarm caused by local change.
