### ISSUE TITLE
Accessing cost data in UnitCommitment.jl

### ISSUE THREAD

**Issue by chengg04** [ANL-CEEESA/UnitCommitment.jl#46]
## Description

(Originally posted on Julia Discourse by Sarah (https://discourse.julialang.org/t/accessing-cost-data-in-unitcommitment-jl/103510). Submitting an issue here under Mathieu's suggestion.)

We are trying to access data for generator cost in the package. In the instance `matpower/case2383wp/2017-02-01`, it seems some of the generators (such as generators 12 and 39) have an empty `cost_segments`, while other generators’ `cost_segments` have nonzero lengths.

Yet, the instance `matpower/case2383wp/2017-02-01` runs without a bug if solve it directly using `UnitCommitment.optimize!(model)`. So I was wondering if there is some behind-the-scene data handling in the source code. I tried to look into the source code, but couldn’t identify anything. 

I also checked the JSON file (https://axavier.org/UnitCommitment.jl/0.3/instances/matpower/case2383wp/). I found that the cost for g12 isn’t empty, while g39 does not exist.

## Steps to Reproduce

MWE:

```
using CSV, DataFrames
using UnitCommitment

instance = UnitCommitment.read_benchmark("matpower/case2383wp/2017-02-01",)
cost = Dict()
for g in 1:length(instance.units)
  unit = instance.units[g]
  cost[g] = unit.cost_segments[1].cost[1]
end
```

Below is the error that is thrown by the MWE.

```
ERROR: BoundsError: attempt to access 0-element Vector{UnitCommitment.CostSegment} at index [1]
Stacktrace:
[1] getindex(A::Vector{UnitCommitment.CostSegment}, i1::Int64)
@ Base .\array.jl:805
[2] top-level scope
@ c:\Users\Guest\MWE.jl:8
```

## System Information
 - Operating System: MacOS Ventura 13.4.1
 - Julia version: 1.6
 - Package version: 0.3.0

**Comment by odow** [comment]
I don't know a definitive answer, but from a browse of the code:
https://github.com/ANL-CEEESA/UnitCommitment.jl/blob/58cc33ac69386983c94a04da956e673b24ada35c/src/transform/initcond.jl#L71-L77

it looks like if the `cost_segments` is `0`, then the cost should be a flat rate of `.min_power_cost`.

Does that help explain?

**Comment by chengg04** [comment]
Yes, this is helpful! I checked the `min_power_cost` of g12, which has an empty `cost_segments`, and got `[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]`, so I can just use 0 as its cost.
