### ISSUE TITLE
Type instability in internal data structures

### ISSUE THREAD

**Issue by mtanneau** [ANL-CEEESA/UnitCommitment.jl#9]
## Description
I've noticed that a lof of internal data structures have fields that are typed `Array{Something}` (where `Something` is, e.g., `Float64`, `Bool`, etc). For instance:
```julia
mutable struct CostSegment
    mw::Array{Float64}
    cost::Array{Float64}
end
```

The issue here is that `Array{Float64}` is actually an abstract type whose dimension is not known
```julia
julia> Array{Float64}
Array{Float64,N} where N
```
i.e., when writing something like `cost_segment.cost`, the compiler has no way of knowing whether this is a vector, matrix, etc..=
Nothing will break down because of this, but the type instability will slow down any function that encounters it; most likely when building models.

Looking at the rest of the code, I believe a lot of these fields should actually be typed as `Vector{Something}`, e.g, 
```julia
mutable struct CostSegment
    mw::Vector{Float64}
    cost::Vector{Float64}
end
```

If those changes would be satisfactory, I can open a PR

**Comment by iSoron** [comment]
Nice catch, thanks for noticing this. Such a PR would be very welcome.
